name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Application
        run: npm start &  # Run app in background

      - name: Wait for App to be Ready
        run: sleep 10  # Wait for app to start (adjust as needed)

      - name: Run Cypress Tests
        run: npx cypress run
